cityofaustin/atd-data-and-performance

- components/js/device-status.js
- components/js/signal-projects.js
Temporarily patch some location pointers while troubleshoot issue with scripting server. Intend to deploy robust fix tomorrow.
> Location pointers

- components/js/signal-timing.js
The retiming dashboard broke this week when we added "planned re-timing for 2019, because we did not have ANNUAL_GOALS defined for those years. With this commit we add annual goals through 2021, although they will probably be subject to change.
We also moved makeMap() to a callback of populateTable(), fixing an async race condition that was causing the dashboard to fail on Safari.
Lastly, we added the zoomHome() plugin to the map and enabled scrollzoom.
> Tweaks for Future Data Collection

- _layouts/table-layout.html
- components/css/publisher.css
- components/js/ops-overview.js
- components/js/publisher.js
- components/js/signal-requests.js
- components/js/signal-timing.js
- components/js/signals-on-flash.js
- publisher.md
Pointing update dataset update dates to the new jobs API. Yayyyy.
> Update Date Fixes

- components/css/dashboard.css
- components/js/signal-projects.js
This commit makes visible the "construction note" in the signal project table. It also points to the new "construction note date" field instead of the modified date of the signal, and we tweaked the badge/marker symbology to make it a little less ugly.
> Make Construction Details More Visible and Stuff

- _layouts/dockless-card-layout.html
- _layouts/homepage-layout.html
- components/js/dockless-data-overview.js
- dockless-data.md
> Separate Dockless Page & Tile

- components/js/device-status.js
use domain path instead of IP.
> Update device-status.js 

- _layouts/signal-requests-layout.html
- _layouts/signal-timing-layout.html
> Add warning banners while data integration isn't updating

- package-lock.json
- package.json
- webpackjs/components/MicromobilityData/DateRangeSelect.js
- webpackjs/components/MicromobilityData/index.js
Fixes #298 
Fixes #301 
Fixes security vulnerability by updating lodash
> 298 browser testing

- components/js/signal-projects.js
- components/js/signals-on-flash.js
Fixes #321 
Note: I started this branch with the code from [this existing pull request](https://github.com/cityofaustin/transportation.austintexas.io/pull/320), so it includes all those updates as well.
> 321 traffic signal monitor date fix

- components/css/dashboard.css
- components/js/signal-timing.js
> green for positive travel time

- components/js/ops-overview.js
- components/js/publisher.js
- components/js/signal-timing.js
- components/js/signals-on-flash.js
- webpackjs/components/MicromobilityData/UpdateDate.js
> updated transportation-data URLs

- components/js/ops-overview.js
- package-lock.json
> fixed signal timing NaN error

- components/js/signal-projects.js
Fixes #327 
If a record doesn't have an updated date, the updated field is not displayed at all (rather than showing "Updated: NaN").
Also formatted the code for this file.
I added a comment in the code in GitHub to show the section that I actually changed. Sorry if it's hard to read due to all the formatting changes! I basically just added a logical statement to only show the data if it exists within a record.
> fixed NaN error and formatted code

- webpackjs/components/MicromobilityData/index.js
> under construction banner

- webpackjs/components/MicromobilityData/index.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/2054
> removed under construction alert

- _layouts/homepage-layout.html
- data-tracker.md
Closes https://github.com/cityofaustin/atd-data-tech/issues/3636
> Add redirect for /data-tracker

- components/js/signal-projects.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/4005
> check for data before rendering

- webpackjs/components/About/people.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/3993
> update people config

- components/js/device-status.js
- components/js/signal-projects.js
- components/js/signal-requests.js
- components/js/signal-timing.js
- components/js/signals-on-flash.js
In order to complete [#4471](https://github.com/cityofaustin/atd-data-tech/issues/4471), we need to update the dashboards to use socrata's native location column rather than named latitude and longitude columns. Don't ask me why I didn't do that in the first place—it was a long time ago.
> Use socrata location field instead of named latitude/longitude fields

- _layouts/signals-on-flash-layout.html
- components/js/signals-on-flash.js
- Fixes [#4958](https://github.com/cityofaustin/atd-data-tech/issues/4958)
- Handles Socrata's Point geometry types
> Traffic Signal Monitor: Updates for compatibility with new Knack ETLs

- components/js/signal-timing.js
fixes [#7145](https://github.com/cityofaustin/atd-data-tech/issues/7145)
> Add FY 2022 goals to signal timing dashboard

- components/js/signal-timing.js
fixes [#7145](https://github.com/cityofaustin/atd-data-tech/issues/7145)
> Add FY 2022 goals to signal timing dashboard 

- webpackjs/components/MicromobilityData/index.js
Fixes [#7274](https://github.com/cityofaustin/atd-data-tech/issues/7274)
> Fixes micromobility dashboard issue due to 311 dataset re-location
